export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const AJAX_CALL_CLEAR = 'AJAX_CALL_CLEAR';

export const LOAD_APPS_REQUEST = 'LOAD_APPS_REQUEST';
export const LOAD_APPS_SUCCESS = 'LOAD_APPS_SUCCESS';

export const LOAD_APPS_BY_ROLE_REQUEST = 'LOAD_APPS_BY_ROLE_REQUEST';
export const LOAD_APPS_BY_ROLE_SUCCESS = 'LOAD_APPS_BY_ROLE_SUCCESS';

export const ADMIN_BULK_PERMISSIONS_SAVE_REQUEST = 'ADMIN_BULK_PERMISSIONS_SAVE_REQUEST';
export const ADMIN_BULK_PERMISSIONS_SAVE_COMPLETE = 'ADMIN_BULK_PERMISSIONS_SAVE_COMPLETE';

export const CREATE_APP_REQUEST = 'CREATE_APP_REQUEST';
export const CREATE_APP_SUCCESS = 'CREATE_APP_SUCCESS';

export const CREATE_GROUP_REQUEST = 'CREATE_GROUP_REQUEST';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_FAIL = 'CREATE_GROUP_FAIL';

export const LOAD_USER_APPS_REQUEST = 'LOAD_USER_APPS_REQUEST';
export const LOAD_USER_APPS_SUCCESS = 'LOAD_USER_APPS_SUCCESS';

export const USER_APPS_LOADING = 'USER_APPS_LOADING';
export const LOAD_ADMIN_DATA_REQUEST = 'LOAD_ADMIN_DATA_REQUEST';
export const LOAD_ADMIN_DATA_SUCCESS = 'LOAD_ADMIN_DATA_SUCCESS';

export const LOAD_APP_MEMBERS_MULTI_REQUEST = 'LOAD_APP_MEMBERS_MULTI_REQUEST';
export const LOAD_APP_MEMBERS_MULTI_SUCCESS = 'LOAD_APP_MEMBERS_MULTI_SUCCESS';

export const LOAD_APP_MEMBERS_REQUEST = 'LOAD_APP_MEMBERS_REQUEST';
export const LOAD_APP_MEMBERS_SUCCESS = 'LOAD_APP_MEMBERS_SUCCESS';

export const ADD_APP_MEMBERS_REQUEST = 'ADD_APP_MEMBERS_REQUEST';
export const ADD_APP_MEMBERS_COMPLETE = 'ADD_APP_MEMBERS_COMPLETE';

export const DELETE_APP_MEMBER_REQUEST = 'DELETE_APP_MEMBER_REQUEST';
export const DELETE_APP_MEMBER_COMPLETE = 'DELETE_APP_MEMBER_COMPLETE';

export const DELETE_APP_REQUEST = 'DELETE_APP_REQUEST';
export const DELETE_APP_COMPLETE = 'DELETE_APP_COMPLETE';

export const UPDATE_APP_MEMBER_REQUEST = 'UPDATE_APP_MEMBER_REQUEST';
export const UPDATE_APP_MEMBER_COMPLETE = 'UPDATE_APP_MEMBER_COMPLETE';

export const LOAD_VERSIONS_REQUEST = 'LOAD_VERSIONS_REQUEST';
export const LOAD_VERSIONS_SUCCESS = 'LOAD_VERSIONS_SUCCESS';

export const CLEAR_VERSIONS_REQUEST = 'CLEAR_VERSIONS_REQUEST';

export const UPLOAD_VERSION_REQUEST = 'UPLOAD_VERSION_REQUEST';
export const UPLOAD_VERSION_SUCCESS = 'UPLOAD_VERSION_SUCCESS';

export const LABEL_VERSION_REQUEST = 'LABEL_VERSION_REQUEST';
export const LABEL_VERSION_SUCCESS = 'LABEL_VERSION_SUCCESS';


export const SAVE_APP_META_REQUEST = 'SAVE_APP_META_REQUEST';
export const SAVE_APP_META_COMPLETE = 'SAVE_APP_META_COMPLETE';

export const LOAD_USERS_REQUEST = 'LOAD_USERS_REQUEST';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';

export const LOAD_GROUPS_REQUEST = 'LOAD_GROUPS_REQUEST';
export const LOAD_GROUPS_SUCCESS = 'LOAD_GROUPS_SUCCESS';

export const SHOW_APP_NOTIFICATION = 'SHOW_APP_NOTIFICATION';
export const CLEAR_APP_NOTIFICATION = 'CLEAR_APP_NOTIFICATION';

export const SHOW_ADMIN_NOTIFICATION = 'SHOW_ADMIN_NOTIFICATION';
export const CLEAR_ADMIN_NOTIFICATION = 'CLEAR_ADMIN_NOTIFICATION';

export const LOAD_USER_ID_REQUEST = 'LOAD_USER_ID_REQUEST';
export const LOAD_USER_ID_SUCCESS = 'LOAD_USER_ID_SUCCESS';

export const EDIT_WIDGET = 'EDIT_WIDGET';
export const LOCAL_DATA_LOADED = 'LOCAL_DATA_LOADED';
export const SAVE_NEW_DASHBOARD = 'SAVE_NEW_DASHBOARD';
export const UPDATE_DASHBOARD = 'UPDATE_DASHBOARD';
export const LOAD_DASHBOARD = 'LOAD_DASHBOARD';
export const DASHBOARD_LOADING = 'DASHBOARD_LOADING';
export const DASHBOARD_LOADED = 'DASHBOARD_LOADED';
export const DASHBOARD_SAVING = 'DASHBOARD_SAVING';
export const DASHBOARD_SAVED = 'DASHBOARD_SAVED';
export const DASHBOARD_NAME_CHANGED = 'DASHBOARD_NAME_CHANGED';
export const DASHBOARD_SHOW_SETTINGS_PANE = 'DASHBOARD_SHOW_SETTINGS_PANE';
export const DASHBOARD_COLLAPSE_SETTINGS_PANE = 'DASHBOARD_COLLAPSE_SETTINGS_PANE';
export const REGISTER_WIDGET_CONTROLS = 'REGISTER_WIDGET_CONTROLS';

export const DASHBOARD_DATA_LOAD_REQUEST = 'DASHBOARD_DATA_LOAD_REQUEST';
export const DASHBOARD_DATA_LOADED = 'DASHBOARD_DATA_LOADED';
export const DASHBOARD_DATA_UPDATE = 'DASHBOARD_DATA_UPDATE';
export const DASHBOARD_DATA_BEGIN_LOAD = 'DASHBOARD_DATA_BEGIN_LOAD';
export const DASHBOARD_DATA_LOAD_IN_PROGRESS = 'DASHBOARD_DATA_LOAD_IN_PROGRESS';
export const DASHBOARD_UPDATE_CONFIG_ITEMS = 'DASHBOARD_UPDATE_CONFIG_ITEMS';
export const DASHBOARD_CONFIGURATION_CHANGED = 'DASHBOARD_CONFIGURATION_CHANGED';
export const DASHBOARD_VERSIONS_LOADED = 'DASHBOARD_VERSIONS_LOADED';
export const WIDGET_REGISTER_URL = 'WIDGET_REGISTER_URL';


export const WIDGET_REGISTER = 'WIDGET_REGISTER';
export const WIDGET_DEREGISTER = 'WIDGET_DEREGISTER';
export const WIDGET_DATA_FILTER_CHANGED = 'WIDGET_DATA_FILTER_CHANGED';
export const WIDGET_SET_MASTER_WIDGET = 'WIDGET_SET_MASTER_WIDGET';
export const WIDGET_IFRAME_CHANGED = 'WIDGET_IFRAME_CHANGED';

export const DASHBOARD_REDIRECT = 'DASHBOARD_REDIRECT';
export const DASHBOARD_REDIRECT_COMPLETED = 'DASHBOARD_REDIRECT_COMPLETED';

export const SHOW_DASHBOARD_NOTIFICATION = 'SHOW_DASHBOARD_NOTIFICATION';
export const CLEAR_DASHBOARD_NOTIFICATION = 'CLEAR_DASHBOARD_NOTIFICATION';

export const MAXIMIZE_DASHBOARD = 'MAXIMIZE_DASHBOARD';
export const RESIZE_COMPONENTS = 'RESIZE_COMPONENTS';
export const RESIZE_EVENT_CONSUMED = 'RESIZE_EVENT_CONSUMED';
export const TOGGLE_WIDGET_HEADERS = 'TOGGLE_WIDGET_HEADERS';
export const RESET_DASHBOARD = 'RESET_DASHBOARD';
export const DASHBOARD_UPDATE_INTERVAL_SET = 'DASHBOARD_UPDATE_INTERVAL_SET';
export const SAVE_LOCAL_FILE_UPLOAD = 'SAVE_LOCAL_FILE_UPLOAD';

export const LOAD_STORE_COLLECTIONS = 'LOAD_STORE_COLLECTIONS';
export const STORE_COLLECTIONS_LOADED = 'STORE_COLLECTIONS_LOADED';
export const CREATE_USER_COLLECTION = 'CREATE_USER_COLLECTION';
export const LOAD_COLLECTION_CONTENTS = 'LOAD_COLLECTION_CONTENTS';
export const DELETE_COLLECTION_FILE = 'DELETE_COLLECTION_FILE';
export const SAVE_COLLECTION_FILE = 'SAVE_COLLECTION_FILE';
export const COLLECTION_CONTENTS_LOADED = 'COLLECTION_CONTENTS_LOADED';
export const COLLECTION_ERROR = 'COLLECTION_ERROR';
export const RESET_COLLECTION_STATE = 'RESET_COLLECTION_STATE';
export const LOAD_COLLECTION_MEMBERS_REQUEST = 'LOAD_COLLECTION_MEMBERS_REQUEST';
export const LOAD_COLLECTION_MEMBERS_SUCCESS = 'LOAD_COLLECTION_MEMBERS_SUCCESS';

export const ADD_COLLECTION_MEMBERS_REQUEST = 'ADD_COLLECTION_MEMBERS_REQUEST';
export const DELETE_COLLECTION_MEMBER_REQUEST = 'DELETE_COLLECTION_MEMBER_REQUEST';
export const UPDATE_COLLECTION_MEMBER_REQUEST = 'UPDATE_COLLECTION_MEMBER_REQUEST';


export const USER_PREFERENCES_REQUEST = 'USER_PREFERENCES_REQUEST';
export const USER_PREFERENCES_LOADED = 'USER_PREFERENCES_LOADED';
export const SAVE_USER_PREFERENCES = 'SAVE_USER_PREFERENCES';

export const TOGGLE_APPNAVBAR_SHOW_MENU = "TOGGLE_APPNAVBAR_SHOW_MENU";
export const FILTER_APPS_AND_SORT = "FILTER_APPS_AND_SORT";
export const SORT_FILTERED_APPS = "SORT_FILTERED_APPS";
export const RESET_FILTERED_APPS = "RESET_FILTERED_APPS";

export const LOAD_FAVOURITES_REQUEST = "LOAD_FAVOURITES_REQUEST";
export const LOAD_FAVOURITES_SUCCESS = "LOAD_FAVOURITES_SUCCESS";
export const UNFAVOURITE_APP_REQUEST = "UNFAVOURITE_APP_REQUEST";
export const UNFAVOURITE_APP_SUCCESS = "UNFAVOURITE_APP_SUCCESS";
export const FAVOURITE_APP_REQUEST = "FAVOURITE_APP_REQUEST";
export const FAVOURITE_APP_SUCCESS = "FAVOURITE_APP_SUCCESS";
